module.exports = {
  "Cà Mau": [
    "Cái Nước",
    "Dam Doi",
    "Nam Căn",
    "Ngoc Hien",
    "Phu Tan",
    "TP. Cà Mau",
    "Thới Bình",
    "Tran Van Thoi",
    "U Minh",
  ],
  "Bạc Liêu": [
    "Giá Rai",
    "Hong Dan",
    "Hòa BÌnh",
    "Phước Long",
    "TP. Bạc Liêu",
    "Vĩnh Lợi",
    "Đông Hải",
  ],
  "Sóc Trăng": [
    "Châu Thành",
    "Cù Lao Dung",
    "Ke Sach",
    "Long Phú",
    "My Xuyen",
    "Mỹ Tú",
    "Ngã Năm",
    "Soc Trang",
    "Thanh Trì",
    "Tran De",
    "Vĩnh Châu",
  ],
  "Kiên Giang": [
    "An Biên",
    "An Minh",
    "Chau Thanh",
    "Giang Thanh",
    "Giong Rieng",
    "Go Quao",
    "Ha Tien",
    "Hon Dat",
    "Kien Hai",
    "Kien Luong",
    "Phu Quoc",
    "Rach Gia",
    "Tan Hiep",
    "U Minh Thượng",
    "Vĩnh Thuận",
  ],
  "Trà Vinh": [
    "Cang Long",
    "Cau Ke",
    "Cau Ngang",
    "Châu Thành",
    "Duyên Hải",
    "Tieu Can",
    "Tra Cu",
    "Trà Vinh",
  ],
  "Hậu Giang": [
    "Chau Thanh",
    "Chau Thanh A",
    "Long Mỹ",
    "Nga Bay",
    "Phung Hiep",
    "Vi Thanh",
    "Vi Thuy",
  ],
  "Cần Thơ": [
    "Binh Thuy",
    "Cai Rang",
    "Co Do",
    "Ninh Kieu",
    "O Mon",
    "Phong Dien",
    "Thoi Lai",
    "Thot Not",
    "Vinh Thanh",
  ],
  "Bến Tre": [
    "Ba Tri",
    "Ben Tre",
    "Binh Dai",
    "Chau Thanh",
    "Cho Lach",
    "Giong Trom",
    "Mo Cay Bac",
    "Mo Cay Nam",
    "Thanh Phu",
  ],
  "Vĩnh Long": [
    "Bình Minh",
    "Bình Tân",
    "Long Hổ",
    "Mang Thít",
    "Tam Bình",
    "Trà Ơn",
    "Vĩnh Long",
    "Vũng Liêm",
  ],
  "Đồng Tháp": [
    "Cao Lanh",
    "Chau Thanh",
    "Hong Ngu",
    "Lai Vung",
    "Lap Vo",
    "Sa Dec",
    "TP Cao Lanh",
    "TP. Hong Ngu",
    "Tam Nong",
    "Tan Hong",
    "Thanh Binh",
    "Thap Muoi",
  ],
  "Tiền Giang": [
    "Chau Thanh",
    "Chợ Gạo",
    "Cái Bè",
    "Cái Lậy",
    "Gò Công",
    "Gò Công Tây",
    "Gò Công Đông",
    "Mỹ Tho",
    "Tân Phú Đông",
    "Tân Phước",
  ],
  "An Giang": [
    "An Phu",
    "Chau Doc",
    "Chau Phu",
    "Chau Thanh",
    "Cho Moi",
    "Long Xuyen",
    "Phu Tan",
    "Tan Chau",
    "Thoai Son",
    "Tinh Bien",
    "Tri Ton",
  ],
  "Bà Rịa - Vũng Tàu": [
    "Ba Ria",
    "Chau Duc",
    "Con Dao",
    "Dat Do",
    "Long Dien",
    "Tan Thanh",
    "Vung Tau",
    "Xuyen Moc",
  ],
  "Long An": [
    "Ben Luc",
    "Can Duoc",
    "Can Giuoc",
    "Chau Thanh",
    "Duc Hoa",
    "Duc Hue",
    "Kien Tuong",
    "Moc Hoa",
    "Tan An",
    "Tan Hung",
    "Tan Thanh",
    "Tan Tru",
    "Thanh Hoa",
    "Thu Thua",
    "Vinh Hung",
  ],
  "TP. Hồ Chí Minh": [
    "BÌnh Chánh",
    "Bình Thạnh",
    "Bình Tân",
    "Cần Giờ",
    "Củ Chi",
    "Gò Vấp",
    "Hooc Môn",
    "Nhà Bè",
    "Phú Nhuận",
    "Quận 1",
    "Quận 10",
    "Quận 11",
    "Quận 12",
    "Quận 2",
    "Quận 3",
    "Quận 4",
    "Quận 6",
    "Quận 7",
    "Quận 8",
    "Quận 9",
    "Quậng 5",
    "Thủ Đức",
    "Tân Bình",
    "Tân Phú",
  ],
  "Đồng Nai": [
    "Bien Hoa",
    "Cam My",
    "Dinh Quan",
    "Long Khanh",
    "Long Thanh",
    "Nhon Trach",
    "Tan Phu",
    "Thong Nhat",
    "Trang Bom",
    "Vinh Cuu",
    "Xuan Loc",
  ],
  "Bình Thuận": [
    "Bac Binh",
    "Duc Linh",
    "Ham Tan",
    "Ham Thuan Bac",
    "Ham Thuan Nam",
    "La Gi",
    "Phan Thiet",
    "Phu Quy",
    "Tanh Linh",
    "Tuy Phong",
  ],
  "Bình Dương": [
    "Ben Cat",
    "Dau Tieng",
    "Di An",
    "Phu Giao",
    "Tan Uyen",
    "Thu Dau Mot",
    "Thuan An",
  ],
  "Tây Ninh": [
    "Ben Cau",
    "Chau Thanh",
    "Duong Minh Chau",
    "Go Dau",
    "Hoa Thanh",
    "Tan Bien",
    "Tan Chau",
    "Tay Ninh",
    "Trang Bang",
  ],
  "Bình Phước": [
    "Binh Long",
    "Bu Dang",
    "Bu Dop",
    "Bu Gia Map",
    "Chon Thanh",
    "Dong Phu",
    "Dong Xoai",
    "Hon Quan",
    "Loc Ninh",
    "Phuoc Long",
  ],
  "Lâm Đồng": [
    "Bao Lam",
    "Bao Loc",
    "Cat Tien",
    "Da Huoai",
    "Da Lat",
    "Da Teh",
    "Dam Rong",
    "Di Linh",
    "Don Duong",
    "Duc Trong",
    "Lac Duong",
    "Lam Ha",
  ],
  "Ninh Thuận": [
    "Bac Ai",
    "Ninh Hai",
    "Ninh Phuoc",
    "Ninh Son",
    "Phan Rang-Thap Cham",
    "Thuan Bac",
    "Thuan Nam",
  ],
  "Đắk Nông": [
    "Cu Jut",
    "Dak Glong",
    "Dak Mil",
    "Dak R'Lap",
    "Dak Song",
    "Gia Nghia",
    "Krong No",
    "Tuy Duc",
  ],
  "Khánh Hòa": [
    "Cam Lam",
    "Cam Ranh",
    "Dien Khanh",
    "Khanh Son",
    "Khanh Vinh",
    "Nha Trang",
    "Ninh Hoa",
    "Truong Sa",
    "Van Ninh",
  ],
  "Đắk Lắk": [
    "Buon Don",
    "Buon Ho",
    "Buon Ma Thuot",
    "Cu Kuin",
    "Cu M'gar",
    "Ea H'leo",
    "Ea Kar",
    "Ea Sup",
    "Krong Ana",
    "Krong Bong",
    "Krong Buk",
    "Krong Nang",
    "Krong Pak",
    "Lak",
    "M'Drak",
  ],
  "Phú Yên": [
    "Dong Hoa",
    "Dong Xuan",
    "Phu Hoa",
    "Son Hoa",
    "Song Cau",
    "Song Hinh",
    "Tay Hoa",
    "Tuy An",
    "Tuy Hoa",
  ],
  "Gia Lai": [
    "An Khê",
    "Ayun Pa",
    "Chu Pah",
    "Chu Prong",
    "Chu Puh",
    "Chu Se",
    "Dak Doa",
    "Dak Po",
    "Duc Co",
    "Ia Grai",
    "Ia Pa",
    "KBang",
    "Kong Chro",
    "Krong Pa",
    "Mang Yang",
    "Phu Thien",
    "Pleiku",
  ],
  "Bình Định": [
    "An Lao",
    "An Nhơn",
    "Hoai An",
    "Hoai Nhon",
    "Phu Cat",
    "Phu My",
    "Qui Nhon",
    "Tay Son",
    "Tuy Phuoc",
    "Van Canh",
    "Vinh Thanh",
  ],
  "Kon Tum": [
    "Dak Glei",
    "Dak Ha",
    "Dak To",
    "Kon Plong",
    "Kon Ray",
    "Kon Tum",
    "Ngoc Hoi",
    "Sa Thay",
    "Tu Mo Rong",
  ],
  "Quảng Ngãi": [
    "Ba To",
    "Binh Son",
    "Duc Pho",
    "Ly Son",
    "Minh Long",
    "Mo Duc",
    "Nghia Hanh",
    "Quang Ngai",
    "Son Ha",
    "Son Tay",
    "Son Tinh",
    "Tay Tra",
    "Tra Bong",
    "Tu Nghia",
  ],
  "Quảng Nam": [
    "Bac Tra My",
    "Dai Loc",
    "Dien Ban",
    "Dong Giang",
    "Duy Xuyen",
    "Hiep Duc",
    "Hoi An",
    "Nam Giang",
    "Nam Tra My",
    "Nong Son",
    "Nui Thanh",
    "Phu Ninh",
    "Phuoc Son",
    "Que Son",
    "Tam Ky",
    "Tay Giang",
    "Thang Binh",
    "Tien Phuoc",
  ],
  "Đà Nẵng": [
    "Cam Le",
    "Hai Chau",
    "Hoa Vang",
    "Hoang Sa",
    "Lien Chieu",
    "Ngu Hanh Son",
    "Son Tra",
    "Thanh Khe",
  ],
  "Thừa Thiên Huế": [
    "A Lưới",
    "Hue",
    "Hương Thủy",
    "Hương Trà",
    "Nam Đồng",
    "Phong Điền",
    "Phu Vang",
    "Phú Lộc",
    "Quang Dien",
  ],
  "Quảng Trị": [
    "Cam Lo",
    "Con Co",
    "Da Krong",
    "Dong Ha",
    "Gio Linh",
    "Hai Lang",
    "Huong Hoa",
    "Quang Tri",
    "Trieu Phong",
    "Vinh Linh",
  ],
  "Quảng Bình": [
    "Bo Trach",
    "Dong Hoi",
    "Le Thuy",
    "Minh Hoa",
    "Quang Ninh",
    "Quang Trach",
    "Tuyen Hoa",
  ],
  "Hà Tĩnh": [
    "Cam Xuyen",
    "Can Loc",
    "Duc Tho",
    "Ha Tinh",
    "Hong Linh",
    "Huong Khe",
    "Huong Son",
    "Ky Anh",
    "Loc Ha",
    "Nghi Xuan",
    "Thach Ha",
    "Vu Quang",
  ],
  "Nghệ An": [
    "Anh Son",
    "Con Cuong",
    "Cua Lo",
    "Dien Chau",
    "Do Luong",
    "Hoang Mai",
    "Hung Nguyen",
    "Ky Son",
    "Nam Dan",
    "Nghi Loc",
    "Nghia Dan",
    "Que Phong",
    "Quy Chau",
    "Quy Hop",
    "Quynh Luu",
    "Tan Ky",
    "Thai Hoa",
    "Thanh Chuong",
    "Tuong Duong",
    "Vinh",
    "Yen Thanh",
  ],
  "Thanh Hóa": [
    "Ba Thuoc",
    "Bỉm Sơn",
    "Cẩm Thủy",
    "Hoằng Hóa",
    "Hà Trung",
    "Hậu Lộc",
    "Lang Chanh",
    "Mường Lát",
    "Nga Sơn",
    "Ngọc Lạc",
    "Nhu Thanh",
    "Nhu Xuan",
    "Nông Cống",
    "Quan Hoa",
    "Quan Son",
    "Quảng Xương",
    "Sầm Sơn",
    "Thanh Hóa",
    "Thiệu hóa",
    "Thường Xuân",
    "Thạch Thanh",
    "Thọ Xuân",
    "Triệu Sơn",
    "Tĩnh Gia",
    "Vĩnh Lộc",
    "Yên Định",
    "Đông Sơn",
  ],
  "Hải Phòng": [
    "An Dương",
    "An Lao",
    "Bach Long Vi",
    "Cat Hai",
    "Do Son",
    "Duong Kinh",
    "Hai An",
    "Hong Bang",
    "Kien An",
    "Kien Thuy",
    "Le Chan",
    "Ngo Quyen",
    "Thuy Nguyen",
    "Tien Lang",
    "Vinh Bao",
  ],
  "Ninh Bình": [
    "Gia Vien",
    "Hoa Lu",
    "Kim Son",
    "Nho Quan",
    "Ninh Binh",
    "Tam Diep",
    "Yen Khanh",
    "Yen Mo",
  ],
  "Nam Định": [
    "Giao Thuy",
    "Hai Hau",
    "My Loc",
    "Nam Dinh",
    "Nam Truc",
    "Nghia Hung",
    "Truc Ninh",
    "Vu Ban",
    "Xuan Truong",
    "Y Yen",
  ],
  "Thái Bình": [
    "Hưng Hà",
    "Kiến Xương",
    "Quỳnh Phụ",
    "Thái Bình",
    "Thái Thụy",
    "Tiền Hải",
    "Vũ Thư",
    "Đông Hưng",
  ],
  "Hà Nam": [
    "Binh Luc",
    "Duy Tien",
    "Kim Bang",
    "Ly Nhan",
    "Phu Ly",
    "Thanh Liem",
  ],
  "Hòa Bình": [
    "Cao Phong",
    "Da Bac",
    "Hoa Binh",
    "Kim Boi",
    "Ky Son",
    "Lac Son",
    "Lac Thuy",
    "Luong Son",
    "Mai Chau",
    "Tan Lac",
    "Yen Thuy",
  ],
  "Hà Nội": [
    "Ba Dinh",
    "Ba Vi",
    "Cau Giay",
    "Chuong My",
    "Dan Phuong",
    "Dong Anh",
    "Dong Da",
    "Gia Lam",
    "Ha Dong",
    "Hai Ba Trung",
    "Hoai Duc",
    "Hoan Kiem",
    "Hoang Mai",
    "Long Bien",
    "Me Linh",
    "My Duc",
    "Phu Xuyen",
    "Phuc Tho",
    "Quoc Oai",
    "Soc Son",
    "Son Tay",
    "Tay Ho",
    "Thach That",
    "Thanh Oai",
    "Thanh Tri",
    "Thanh Xuan",
    "Thuong Tin",
    "Tu Liem",
    "Ung Hoa",
  ],
  "Hải Dương": [
    "Binh Giang",
    "Cam Giang",
    "Chi Linh",
    "Gia Loc",
    "Hai Duong",
    "Kim Thanh",
    "Kinh Mon",
    "Nam Sach",
    "Ninh Giang",
    "Thanh Ha",
    "Thanh Mien",
    "Tu Ky",
  ],
  "Bắc Ninh": [
    "Bac Ninh",
    "Gia Binh",
    "Luong Tai",
    "Que Vo",
    "Thuan Thanh",
    "Tien Du",
    "Tu Son",
    "Yen Phong",
  ],
  "Sơn La": [
    "Bac Yen",
    "Mai Son",
    "Moc Chau",
    "Muong La",
    "Phu Yen",
    "Quynh Nhai",
    "Son La",
    "Song Ma",
    "Sop Cop",
    "Thuan Chau",
    "Yen Chau",
  ],
  "Quảng Ninh": [
    "Ba Che",
    "Binh Lieu",
    "Cam Pha",
    "Co To",
    "Dam Ha",
    "Dong Trieu",
    "Ha Long",
    "Hai Ha",
    "Hoanh Bo",
    "Mong Cai",
    "Quang Yen",
    "Tien Yen",
    "Uong Bi",
    "Van Don",
  ],
  "Hưng Yên": [
    "An Thi",
    "Hung Yen",
    "Khoai Chau",
    "Kim Dong",
    "My Hao",
    "Phu Cu",
    "Tien Lu",
    "Van Giang",
    "Van Lam",
    "Yen My",
  ],
  "Phú Thọ": [
    "Cam Khe",
    "Doan Hung",
    "Ha Hoa",
    "Lam Thao",
    "Phu Ninh",
    "Phu Tho",
    "Tam Nong",
    "Tan Son",
    "Thanh Ba",
    "Thanh Son",
    "Thanh Thuy",
    "Viet Tri",
    "Yen Lap",
  ],
  "Bắc Giang": [
    "Bac Giang",
    "Hiep Hoa",
    "Lang Giang",
    "Luc Nam",
    "Luc Ngan",
    "Son Dong",
    "Tan Yen",
    "Viet Yen",
    "Yen Dung",
    "Yen The",
  ],
  "Vĩnh Phúc": [
    "Bình Xuyên",
    "Lập Thạch",
    "Phúc Yên",
    "Sông Lô",
    "Tam Duong",
    "Tam Đảo",
    "Vĩnh Tường",
    "Vĩnh Yên",
    "Yên Lạc",
  ],
  "Điện Biên": [
    "Dien Bien",
    "Dien Bien Dong",
    "Dien Bien Phu",
    "Muong Ang",
    "Muong Cha",
    "Muong Lay",
    "Muong Nhe",
    "Nam Po",
    "Tua Chua",
    "Tuan Giao",
  ],
  "Thái Nguyên": [
    "Dong Hy",
    "Phú Bình",
    "Phú Lương",
    "Phổ Yên",
    "Sông Công",
    "Thái Nguyên",
    "Võ Nhai",
    "Đinh Hoa",
    "Đại Từ",
  ],
  "Yên Bái": [
    "Lục Yên",
    "Mù Căng Chải",
    "Nghĩa Lộ",
    "Tram Tầu",
    "Trấn Yên",
    "Văn Chấn",
    "Văn Yên",
    "Yên Bài",
    "Yên Bình",
  ],
  "Lạng Sơn": [
    "Bac Son",
    "Binh Gia",
    "Cao Loc",
    "Chi Lang",
    "Dinh Lap",
    "Huu Lung",
    "Lang Son",
    "Loc Binh",
    "Trang Dinh",
    "Van Lang",
    "Van Quan",
  ],
  "Tuyên Quang": [
    "Chiêm Hóa",
    "Hàm Yên",
    "Lam Bình",
    "Na Hang",
    "Sơn Dương",
    "Tuyên Quang",
    "Yên Sơn",
  ],
  "Lai Châu": [
    "Lai Chau",
    "Muong Te",
    "Nam Nhun",
    "Phong Tho",
    "Sin Ho",
    "Tam Duong",
    "Tan Uyen",
    "Than Uyen",
  ],
  "Bắc Kạn": [
    "Ba Be",
    "Bac Kan",
    "Bach Thong",
    "Cho Don",
    "Cho Moi",
    "Na Ri",
    "Ngan Son",
    "Pac Nam",
  ],
  "Lào Cai": [
    "Bac Ha",
    "Bao Thang",
    "Bao Yen",
    "Bat Xat",
    "Lao Cai",
    "Muong Khuong",
    "Sa Pa",
    "Si Ma Cai",
    "Van Ban",
  ],
  "Hà Giang": [
    "Bac Me",
    "Bac Quang",
    "Dong Van",
    "Ha Giang",
    "Hoang Su Phi",
    "Meo Vac",
    "Quan Ba",
    "Quang Binh",
    "Vi Xuyen",
    "Xin Man",
    "Yen Minh",
  ],
  "Cao Bằng": [
    "Bao Lac",
    "Bao Lam",
    "Cao Bang",
    "Ha Lang",
    "Ha Quang",
    "Hoa An",
    "Nguyen Binh",
    "Phuc Hoa",
    "Quang Uyen",
    "Thach An",
    "Thong Nong",
    "Tra Linh",
    "Trung Khanh",
  ],
};
